### PR TITLE
Web scrapper shaheer

### PR DESCRIPTION
**Pull request by Shaheerairaj**
Scripts successfully grabs all ads for each page.

Currently, it is able to go through the pages dynamically but not through the car brands. This may have to be kept manual as there is risk of being flagged and blocked by the host websites.

### CODE REVIEW

**Comment by ohinson01** [comment]
@Shaheerairaj I was trying out the web-scrapper.py file to see how it worked and have a question about it. Why choose to open multiple pages with the webdriver instead of going through the pages with the arrows? I was just curious if that way is more efficient and not performance heavy if you just went through the pages one by one with the Next button. 

image

**Comment by Shaheerairaj** [comment]
You're right, this is more performance heavy and a better solution could be to flip through the pages by clicking on the buttons below.

The method where I use the URL to flip through pages was something I had learned a while back for simpler websites which didn't require selenium and it was the first thing that came to mind. The thought of using the buttons to flip through pages didn't occur to me till I saw your implementation yesterday, but I chose not to change it for now until I had a working solution.

Seeing as we still have some time until this phase is planned to be completed, I can test out using your method.

**Comment by ohinson01** [comment]
Ok. I am not sure if my implantation is any better. It takes a really long time to flip through each page to gather information. I am seeing if there is a better way to gather the data, but haven't found one yet. Let me know how your implantation turns out using my method. 

I also copied a piece of your code into mine to find the last page of the website. I was really stumped until I saw the code you added. It really helped me in flipping through all pages.

**Comment by ohinson01** [comment]
I also never knew you could log things in Python until I saw what you implemented. I might also include that in my code to see how it works.

**Pull request merged**
