### PR TITLE
Updated README with disclaimer for use of code

### PR DESCRIPTION
**Pull request by ohinson01**
I added a disclaimer for our project so that people know that this code should only be used for learning purpose and not be used for anything dangerous or something like that. Feel free to also update as this is just a safety measure for us.

### CODE REVIEW

**Review by Shaheerairaj — COMMENTED** [review]
I'm not sure if it's a good idea to publish the Terms of use line. Companies don't really like people scrapping their data (although we are only doing it on a small scale) so I don't really want to release the information of where we are sourcing our data.

In fact, we should update our scripts to remove the base URL and call it from an environment variable instead of hard coding it into the scripts.

What are your thoughts?

**Comment by ohinson01** [comment]
Ah ok. I think that would be a good idea to call it from an environment variable. I think that makes sense.

**Comment by ohinson01** [comment]
If you do not want the terms of use line in the README, then I think you can just discard that pull request and just add the disclaimer. 

I added the disclaimer since I was reading up on web scraping. One of the things mentioned is adding this to be extra safe when posting your code to GitHub

Feel free to edit anything you think needs to be added to that disclaimer or anything like that.

**Comment by ohinson01** [comment]
I have now stored the website URL and the location of my Chrome Driver in an environment variable.

**Comment by Shaheerairaj** [comment]
I see that you've made changes to two files, Can I approve changes to one file and not the other?

**Comment by ohinson01** [comment]
I think you can, but I am not 100% sure on that. I know you can choose and pick what changes you want to include, but I have never merged before. I only have experience with pull requests. 

I did see this article about what to do, but I am not sure if it means merging one file and not the other. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-pull-request-commits

**Comment by Shaheerairaj** [comment]
Why did you change your script from a notebook to a .py file? Also, I recommend you change the name of the file.

**Comment by ohinson01** [comment]
After looking at what you added in GitHub as a .py file and then back to my file, I was thinking it looked a bit better that way. I will update the name of the script.

**Comment by ohinson01** [comment]
Also, I like to keep notes as I am coding and what I am adding shows the website as well in Jupyter Notebook.

**Comment by ohinson01** [comment]
Updated file name, but had to create a new PR for it #31

**Comment by ohinson01** [comment]
Feel free to discard the other 2 commits since the new PR has everything in it already.

**Review by Shaheerairaj — APPROVED** [review]

**Pull request closed without merging**
